{
 "title": "Cassandra-AllDC",
 "tags": [ "cassandra" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, cluster)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_stats{cluster=\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_stats{cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
   },
   {
    "name": "percentiles",
    "query": "50thpercentile,98thpercentile,99thpercentile,max"
   },
   {
    "name": "namespace",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, namespace)"
   },
   { "name": "pod_prefix", "query": "cassandra-" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "README",
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "content": "### Cassandra SLA Dashboard\n#### This dashboard provides the following informations :\n_User metrics_\n* __max latencies by percentile__ : read / write / scan\n* __OPS__ : read / write\n* __Disk usage__ : live space / total space\n* __JAVA heap & non heap usage__ : current memory / max allowed\n\n_Advanced metrics_\n* __Pending operations__ :  compactions / flushes\n* __Streaming & CommitLog__ : OPS / throughput\n* __Repair ratio__ : for every keyspace\n* __Memtable statistics__\n* __Row cache__ : hit rates\n* __Thread pools metrics__ : OPS / blocked / pending"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failing or dead nodes",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_statefulset_replicas{namespace=\"$cluster\",statefulset=\"cassandra\"} - kube_statefulset_status_replicas{namespace=\"$cluster\",statefulset=\"cassandra\"}"
      }
     ]
    }
   ]
  },
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:$percentiles\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:$percentiles\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Range Scan Latencies",
   "type": "graph",
   "description": "Local range scan latency",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:rangelatency:$percentiles\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Dropped Message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:droppedmessage:.*:oneminuterate\"}, \"type\", \"$1\", \"name\", \".+:droppedmessage:(.+):oneminuterate\")) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "MAX CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod)(rate(container_cpu_usage_seconds_total{container=\"cassandra\"}[1m]))",
     "legendFormat": "CPU Usage: {{ pod }}"
    },
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{container=\"cassandra\"}[1m]))",
     "legendFormat": "Avg CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Total: {{ datacenter }}"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused.+\"}) by (datacenter)",
     "legendFormat": "Live: {{ datacenter }}"
    }
   ]
  },
  {
   "title": "Timeouts (1 minute rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"}) by (name)",
     "legendFormat": "Number of requests timeouts over 1 min"
    }
   ]
  },
  {
   "title": "READ PATH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:$percentiles\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Read Ops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:oneminuterate\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:totalblockedtasks:count\"}) by (name)",
       "legendFormat": "Blocked request readstage"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:pendingtasks:value\"}) by (name)",
       "legendFormat": "Pending request readstage"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:activetasks:value\"}) by (name)",
       "legendFormat": "Active request readstage"
      },
      {
       "expr": "sum(rate(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:completedtasks:value\"}[5m])) by (name)",
       "legendFormat": "Completed request readstage"
      }
     ]
    },
    {
     "title": "Row Cache (5 minute rate hit/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:rowcachehit:count\"}[5m])) by (table)",
       "legendFormat": "Hit {{ table }}"
      },
      {
       "expr": "sum(rate(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:rowcachemiss:count\"}[5m])) by (table)",
       "legendFormat": "Miss {{ table }}"
      }
     ]
    },
    {
     "title": "Key cache hit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:keycachehitrate:value\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Chunck cache hit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:cache:chunkcache:oneminutehitrate:value\"}) by (name)",
       "legendFormat": "Chunk cache hit rate"
      }
     ]
    },
    {
     "title": "Max nb SSTables per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:sstablesperreadhistogram:$percentiles\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Max Nb Scanned Tombstones",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:tombstonescannedhistogram:$percentiles\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Nb Live SSTables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livesstablecount:value\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Estimated Partition Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", table=~\"$table\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:estimatedpartitionsizehistogram:max\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WRITE PATH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:$percentiles\"}) by (datacenter)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "Write Ops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:oneminuterate\"}) by (datacenter)",
       "legendFormat": "{{ datacenter }}"
      }
     ]
    },
    {
     "title": "Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:totalblockedtasks:count\"}) by (name)",
       "legendFormat": "Blocked request mutationstage"
      },
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:pendingtasks:value\"}) by (name)",
       "legendFormat": "Pending request mutationstage"
      },
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:activetasks:value\"}) by (name)",
       "legendFormat": "Active request mutationstage"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:completedtasks:value\"}) by (name)",
       "legendFormat": "Completed request mutationstage"
      }
     ]
    },
    {
     "title": "CommitLog",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:commitlog:waitingoncommit:oneminuterate\"}) by (name)",
       "legendFormat": "Wait time to commit over 1 min"
      },
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:commitlog:completedtasks:value\"}) by (name)",
       "legendFormat": "Completed CommitLog Task / sec (avg on 5min)"
      }
     ]
    },
    {
     "title": "Memtable OPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:memtableswitchcount:.*\"}) by (datacenter)",
       "legendFormat": "{{ datacenter }}"
      }
     ]
    },
    {
     "title": "Memtable Data Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:allmemtablesheapsize:value\"}) by (datacenter)",
       "legendFormat": "Total heap {{ table }}"
      },
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:allmemtableslivedatasize:value\"}) by (datacenter)",
       "legendFormat": "Live heap {{ table }}"
      }
     ]
    },
    {
     "title": "Waiting Free Memtable Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:waitingonfreememtablespace:max\"}) by (datacenter)",
       "legendFormat": "{{ datacenter }}"
      }
     ]
    }
   ]
  },
  {
   "title": "COMPACTIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:pendingcompactions:value\"}[1m])) by (datacenter)",
       "legendFormat": "Compactions {{ datacenter }}"
      },
      {
       "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:pendingflushes:count\"}) by (datacenter)",
       "legendFormat": "Flush {{ datacenter }}"
      }
     ]
    },
    {
     "title": "Compaction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:compactionbyteswritten:count\"}[3m])) by (datacenter)",
       "legendFormat": "Compactions {{ datacenter }}"
      }
     ]
    }
   ]
  },
  {
   "title": "THREADPOOLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool (Completed over 5 min)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(rate(cassandra_stats{cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.*:completedtasks:value\"}[5m]), \"info\", \"$1 $2\", \"name\", \".+:threadpools:(.+?):(.+?):.+\")) by (info)",
       "legendFormat": "{{ info }}"
      }
     ]
    },
    {
     "title": "Thread Pool (pending & blocked)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(rate(cassandra_stats{cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.+:totalblockedtasks:count\"}[1m]), \"info\", \"$1 $2\", \"name\", \"org:apache:cassandra:metrics:threadpools:(.+?)::(.+?)totalblockedtasks:count\")) by (info)",
       "legendFormat": "Blocked {{ info }}"
      },
      {
       "expr": "sum(label_replace(cassandra_stats{cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.+:pendingtasks:value\"}, \"info\", \"$1 $2\", \"name\", \"org:apache:cassandra:metrics:threadpools:(.+?):(.+?):pendingtasks:value\")) by (info)",
       "legendFormat": "Pending {{ info }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Last GC duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(label_replace(cassandra_stats{cluster=\"$cluster\",name=~\"java:lang:garbagecollector:.+:lastgcinfo:duration\"}, \"info\", \"$1\", \"name\", \"java:lang:garbagecollector:(.+?):lastgcinfo:duration\")) by (info)",
       "legendFormat": "{{ info }}"
      }
     ]
    },
    {
     "title": "JAVA Heap + NonHeap Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(cassandra_stats{cluster=\"$cluster\",name=~\"java:lang:memory:.+:(committed|max|used)\"}, \"info\", \"$1 $2\", \"name\", \"java:lang:memory:(.+?):(.+?)\")) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Live {{ datacenter }}"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Total {{ datacenter }}"
    }
   ]
  },
  {
   "title": "Nb Live SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livesstablecount:value\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Container Read bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Avg Rate"
    },
    {
     "expr": "max(rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Max Rate"
    }
   ]
  },
  {
   "title": "Container Write bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Avg Rate"
    },
    {
     "expr": "max(rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Max Rate"
    }
   ]
  },
  {
   "title": "REPAIRS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repair Ratio (% repaired)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:percentrepaired:value\"}) by (datacenter)",
       "legendFormat": "{{ datacenter }}"
      }
     ]
    }
   ]
  },
  { "title": "COMMUNICATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Streaming",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:streaming:totalincomingbytes:count\"}) by (name)",
     "legendFormat": "Total Incoming B/s"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:streaming:totaloutgoingbytes:count\"}) by (name)",
     "legendFormat": "Total Outgoing B/s"
    }
   ]
  },
  {
   "title": "Timeouts (1 minute rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"}) by (name)",
     "legendFormat": "Number of requests timeouts over 1 min"
    }
   ]
  },
  {
   "title": "Pod Receive bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Transmit bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}