{
 "title": "Cassandra-MWT",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, cluster)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_stats{cluster=\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_stats{cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
   },
   {
    "name": "percentiles",
    "query": "50thpercentile,98thpercentile,99thpercentile,max"
   },
   {
    "name": "namespace",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, namespace)"
   },
   { "name": "pod_prefix", "query": "cassandra-" }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:$percentiles\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:oneminuterate\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "MAX CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod)(rate(container_cpu_usage_seconds_total{container=\"cassandra\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "CPU Usage: {{ pod }}"
    },
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{container=\"cassandra\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Avg CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Total: {{ datacenter }}"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused.+\"}) by (datacenter)",
     "legendFormat": "Live: {{ datacenter }}"
    }
   ]
  },
  {
   "title": "Container Read bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Avg Rate"
    },
    {
     "expr": "max(rate (container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Max Rate"
    }
   ]
  },
  {
   "title": "Container Write bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Avg Rate"
    },
    {
     "expr": "max(rate (container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"cassandra\"}[1m]))",
     "legendFormat": "Max Rate"
    }
   ]
  },
  {
   "title": "Pod Receive bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Pod Transmit bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod_prefix.*\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Live {{ datacenter }}"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (datacenter)",
     "legendFormat": "Total {{ datacenter }}"
    }
   ]
  },
  {
   "title": "Nb Live SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livesstablecount:value\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  }
 ]
}