{
 "title": "KUDO Cassandra Overview",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, namespace)"
   },
   {
    "name": "cluster",
    "query": "label_values(cassandra_stats{namespace=\"$namespace\",name=\"java:lang:memory:heapmemoryusage:used\"}, cluster)"
   },
   {
    "name": "datacenter",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:used\"}, datacenter)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
   },
   {
    "name": "percentiles",
    "query": "50thpercentile,98thpercentile,99thpercentile,max"
   }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "README",
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "content": "### Cassandra SLA Dashboard\n#### This dashboard provides the following informations :\n_User metrics_\n* __max latencies by percentile__ : read / write / scan\n* __OPS__ : read / write\n* __Disk usage__ : live space / total space\n* __JAVA heap & non heap usage__ : current memory / max allowed\n\n_Advanced metrics_\n* __Pending operations__ :  compactions / flushes\n* __Streaming & CommitLog__ : OPS / throughput\n* __Repair ratio__ : for every keyspace\n* __Memtable statistics__\n* __Row cache__ : hit rates\n* __Thread pools metrics__ : OPS / blocked / pending"
    }
   ]
  },
  { "title": "HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Ready Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"[[cluster]]-node\"}"
    }
   ]
  },
  {
   "title": "NotReady Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"[[cluster]]-node\"} - kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"[[cluster]]-node\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", name=~\"java:lang:memory:heapmemoryusage:used\"})"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", name=~\"java:lang:operatingsystem:systemcpuload\"})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"})"
    }
   ]
  },
  {
   "title": "Writes / Sec (1 min rate)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:writelatency:oneminuterate\"})"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "avg(cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:cache:chunkcache:oneminutehitrate:value\"})"
    }
   ]
  },
  {
   "title": "Up endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\",name=\"org:apache:cassandra:net:failuredetector:upendpointcount\"}) / count(cassandra_stats{name=\"org:apache:cassandra:net:failuredetector:upendpointcount\"})"
    }
   ]
  },
  {
   "title": "Down endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\",name=\"org:apache:cassandra:net:failuredetector:downendpointcount\"}) / count(cassandra_stats{name=\"org:apache:cassandra:net:failuredetector:downendpointcount\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", name=~\"java:lang:memory:nonheapmemoryusage:used\"})"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", name=~\"java:lang:operatingsystem:processcpuload\"})"
    }
   ]
  },
  {
   "title": "Last GC duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"java:lang:garbagecollector:concurrentmarksweep:lastgcinfo:duration\"})"
    }
   ]
  },
  {
   "title": "Reads / Sec (1 min rate)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:readlatency:oneminuterate\"})"
    }
   ]
  },
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Range Scan Latencies",
   "type": "graph",
   "description": "Local range scan latency",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:rangelatency:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Dropped Message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:droppedmessage:.*:oneminuterate\"}, \"type\", \"$1\", \"name\", \".+:droppedmessage:(.+):oneminuterate\")) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "MAX CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container_name)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"cassandra-\\\\d+\"}[1m]))",
     "legendFormat": "CPU Usage: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"\\\\s+node-\\\\d+\"}",
     "legendFormat": "Request: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"\\\\w+-node-\\\\d+\"}",
     "legendFormat": "Limits: {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (table)",
     "legendFormat": "Total: {{ table }}"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused.+\"}) by (table)",
     "legendFormat": "Live: {{ table }}"
    }
   ]
  },
  {
   "title": "Timeouts (1 minute rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"}) by (name)",
     "legendFormat": "Number of requests timeouts over 1 min"
    }
   ]
  },
  {
   "title": "Hints Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:hintsservice:hintsfailed:count\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "READ PATH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:readlatency:oneminuterate\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:totalblockedtasks:count\"}) by (name)",
     "legendFormat": "Blocked request readstage"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:pendingtasks:value\"}) by (name)",
     "legendFormat": "Pending request readstage"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:activetasks:value\"}) by (name)",
     "legendFormat": "Active request readstage"
    },
    {
     "expr": "sum(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:readstage:completedtasks:value\"}[5m])) by (name)",
     "legendFormat": "Completed request readstage"
    }
   ]
  },
  {
   "title": "Row Cache (5 minute rate hit/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:rowcachehit:count\"}[5m])) by (table)",
     "legendFormat": "Hit {{ table }}"
    },
    {
     "expr": "sum(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:rowcachemiss:count\"}[5m])) by (table)",
     "legendFormat": "Miss {{ table }}"
    }
   ]
  },
  {
   "title": "Key cache hit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:keycachehitrate:value\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Chunck cache hit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_stats{namespace=\"$namespace\",datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:cache:chunkcache:oneminutehitrate:value\"}) by (name)",
     "legendFormat": "Chunk cache hit rate"
    }
   ]
  },
  {
   "title": "Max nb SSTables per Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:sstablesperreadhistogram:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Max Nb Scanned Tombstones",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:tombstonescannedhistogram:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Nb Live SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livesstablecount:value\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Estimated Partition Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", table=~\"$table\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:estimatedpartitionsizehistogram:max\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  { "title": "WRITE PATH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:$percentiles\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:writelatency:oneminuterate\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:totalblockedtasks:count\"}) by (name)",
     "legendFormat": "Blocked request mutationstage"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:pendingtasks:value\"}) by (name)",
     "legendFormat": "Pending request mutationstage"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:activetasks:value\"}) by (name)",
     "legendFormat": "Active request mutationstage"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:threadpools:request:mutationstage:completedtasks:value\"}) by (name)",
     "legendFormat": "Completed request mutationstage"
    }
   ]
  },
  {
   "title": "CommitLog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:commitlog:waitingoncommit:oneminuterate\"}) by (name)",
     "legendFormat": "Wait time to commit over 1 min"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:commitlog:completedtasks:value\"}) by (name)",
     "legendFormat": "Completed CommitLog Task / sec (avg on 5min)"
    }
   ]
  },
  {
   "title": "Memtable OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:memtableswitchcount:.*\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Memtable Data Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:allmemtablesheapsize:value\"}) by (table)",
     "legendFormat": "Total heap {{ table }}"
    },
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:allmemtableslivedatasize:value\"}) by (table)",
     "legendFormat": "Live heap {{ table }}"
    }
   ]
  },
  {
   "title": "Waiting Free Memtable Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:.*:waitingonfreememtablespace:max\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "COMPACTIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:pendingcompactions:value\"}[1m])) by (table)",
       "legendFormat": "Compactions {{ table }}"
      },
      {
       "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:pendingflushes:count\"}) by (table)",
       "legendFormat": "Flush {{ table }}"
      }
     ]
    },
    {
     "title": "Compaction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:compactionbyteswritten:count\"}[3m])) by (table)",
       "legendFormat": "Compactions {{ table }}"
      }
     ]
    }
   ]
  },
  { "title": "THREADPOOLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "Thread Pool (Completed over 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.*:completedtasks:value\"}[5m]), \"info\", \"$1 $2\", \"name\", \".+:threadpools:(.+?):(.+?):.+\")) by (info)",
     "legendFormat": "{{ info }}"
    }
   ]
  },
  {
   "title": "Thread Pool (pending & blocked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.+:totalblockedtasks:count\"}[1m]), \"info\", \"$1 $2\", \"name\", \"org:apache:cassandra:metrics:threadpools:(.+?)::(.+?)totalblockedtasks:count\")) by (info)",
     "legendFormat": "Blocked {{ info }}"
    },
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"org:apache:cassandra:metrics:threadpools:.+:pendingtasks:value\"}, \"info\", \"$1 $2\", \"name\", \"org:apache:cassandra:metrics:threadpools:(.+?):(.+?):pendingtasks:value\")) by (info)",
     "legendFormat": "Pending {{ info }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Last GC duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(label_replace(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"java:lang:garbagecollector:.+:lastgcinfo:duration\"}, \"info\", \"$1\", \"name\", \"java:lang:garbagecollector:(.+?):lastgcinfo:duration\")) by (info)",
       "legendFormat": "{{ info }}"
      }
     ]
    },
    {
     "title": "JAVA Heap + NonHeap Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=~\"java:lang:memory:.+:(committed|max|used)\"}, \"info\", \"$1 $2\", \"name\", \"java:lang:memory:(.+?):(.+?)\")) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livediskspaceused:count\"}) by (table)",
     "legendFormat": "Live {{ table }}"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:totaldiskspaceused:count\"}) by (table)",
     "legendFormat": "Total {{ table }}"
    }
   ]
  },
  {
   "title": "Nb Live SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:livesstablecount:value\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "REPAIRS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repair Ratio (% repaired)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\", table=~\"$table\", name=~\"org:apache:cassandra:metrics:table:$keyspace:$table:percentrepaired:value\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    }
   ]
  },
  { "title": "COMMUNICATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 } },
  {
   "title": "Streaming",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:streaming:totalincomingbytes:count\"}) by (name)",
     "legendFormat": "Total Incoming B/s"
    },
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:streaming:totaloutgoingbytes:count\"}) by (name)",
     "legendFormat": "Total Outgoing B/s"
    }
   ]
  },
  {
   "title": "Timeouts (1 minute rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{namespace=\"$namespace\", datacenter=\"$datacenter\", cluster=\"$cluster\",name=\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"}) by (name)",
     "legendFormat": "Number of requests timeouts over 1 min"
    }
   ]
  }
 ]
}