apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: kubectl delete instance cassandra --namespace cassandra
    ignoreFailure: true
  - command: kubectl delete operatorversion --all --namespace cassandra
    ignoreFailure: true
  - command: kubectl delete operator cassandra --namespace cassandra
    ignoreFailure: true

#  kuttl doesn't support custom namespace deletes... yet
# delete:
# - apiVersion: kudo.dev/v1beta1
#   kind: Instance
#   metadata:
#     name: cassandra
#     namespace: cassandra
# - apiVersion: kudo.dev/v1beta1
#   kind: OperatorVersion
#   metadata:
#     namespace: cassandra
# - apiVersion: kudo.dev/v1beta1
#   kind: Operator
#   metadata:
#     namespace: cassandra