apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-kubeaddons
  name: cassandra-cluster-monitor
spec:
  endpoints:
    - interval: 30s
      port: prometheus-exporter-port
  namespaceSelector:
    matchNames:
      - test
  selector:
    matchLabels:
      kudo.dev/servicemonitor: "true"
