OVERRIDE_CLUSTER_NAME: "MWT"
NODE_READINESS_PROBE_INITIAL_DELAY_S: 30
JMX_LOCAL_ONLY: true
NODE_DISK_SIZE_GIB: 100
NODE_CPU_MC: "4000"
NODE_CPU_LIMIT_MC: "4000"
NODE_MEM_MIB: "12000"
NODE_MEM_LIMIT_MIB: "12000"
NODE_ANTI_AFFINITY: "true"
PROMETHEUS_EXPORTER_ENABLED: "true"
SERVICE_ACCOUNT_INSTALL: "true"
NODE_TOLERATIONS: |-
  - key: "dedicated"
    value: "cassandra"
    operator: "Equal"
    effect: "NoExecute"
ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
NODE_TOPOLOGY: |-
  - datacenter: dc1
    datacenterLabels:
      dedicated: cassandra
    nodes: 15
    rackLabelKey: failure-domain.beta.kubernetes.io/region
    racks:
      - rack: rack1
        rackLabelValue: us-west-2
  - datacenter: dc2
    datacenterLabels:
      dedicated: cassandra
    nodes: 15
    rackLabelKey: failure-domain.beta.kubernetes.io/region
    racks:
      - rack: rack1
        rackLabelValue: us-west-2
