OVERRIDE_CLUSTER_NAME: "DryRun"
NODE_READINESS_PROBE_INITIAL_DELAY_S: 30
NODE_COUNT: 3
JMX_LOCAL_ONLY: true
NODE_DISK_SIZE_GIB: 20
NODE_CPU_MC: "2000"
NODE_CPU_LIMIT_MC: "2500"
NODE_MEM_MIB: "2048"
NODE_MEM_LIMIT_MIB: "3192"
PROMETHEUS_EXPORTER_ENABLED: "false"
SERVICE_ACCOUNT_INSTALL: "true"
NODE_TOLERATIONS: |-
  - key: "dedicated"
    value: "cassandra"
    operator: "Equal"
    effect: "NoExecute"