FROM cassandra:3.11.6

COPY medusa/cassandra-sudoer /etc/sudoers.d/

COPY medusa/medusa-src /medusa-src

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends sudo libc6-dev libev-dev libssl-dev zlib1g-dev libffi-dev gcc make cmake python3-dev python3-pip python3-setuptools groff vim; \
    sudo pip3 install awscli; \
    cd medusa-src; \
    python3 setup.py  install

CMD [ "sleep", "infinity" ]

USER root