FROM golang:1.14-alpine AS build-env
ADD ./recovery /recovery
WORKDIR /recovery
RUN apk add --no-cache git
ENV GO111MODULE=on
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cassandra-recovery

FROM debian:buster-20200422-slim
COPY --from=build-env /cassandra-recovery /cassandra-recovery/

CMD /cassandra-recovery/cassandra-recovery
