FROM cassandra:3.11.6

COPY medusa/cassandra-sudoer /etc/sudoers.d/

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends sudo libc6-dev libev-dev gcc make cmake python3-dev python3-pip groff vim; \
    sudo pip3 install setuptools wheel; \
    sudo pip3 install awscli cassandra-medusa[S3]==0.6.0

CMD [ "sleep", "infinity" ]

USER root
