apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kudo-manager
  name: kudo-controller-manager-0
  namespace: kudo-system
status:
  containerStatuses:
  - name: manager
    ready: true
    image: docker.io/kudobuilder/controller:v0.14.0-rc1
    # question the use of this image name but provides exactness on what we are testing against 

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.kudo.dev