apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kudo-manager
  name: kudo-controller-manager-0
  namespace: kudo-system
status:
  containerStatuses:
  - name: manager
    ready: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.kudo.dev