apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600
---
apiVersion: kudo.dev/v1beta1
kind: Instance
metadata:
  name: cassandra-stress
  namespace: cassandra
status:
  planStatus:
    deploy:
      name: deploy
      status: COMPLETE