apiVersion: kudo.dev/v1beta1
kind: Instance
metadata:
  name: cassandra
  namespace: cassandra-upgrade-test
status:
  planStatus:
    deploy:
      status: COMPLETE
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-node
  namespace: cassandra-upgrade-test
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kudo-cassandra/cordon"
                    operator: DoesNotExist
status:
  readyReplicas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-topology-lock
  namespace: cassandra-upgrade-test
data:
  last-updated-by: cassandra-node-0