apiVersion: kudo.dev/v1beta1
kind: TestStep
commands:
  - command: cat params.yaml
  - command: kubectl kudo upgrade -n cassandra-upgrade-test --instance cassandra -P params.yaml ../../../../operator/
    namespaced: true
