{{- $root := . -}}
{{ range $i, $v := until (int .Params.NODE_COUNT) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-node-{{ $v }}
spec:
  template:
    spec:
      serviceAccountName: {{ $root.Name }}-node-backup
      containers:
        - name: backup
          image: bitnami/kubectl:{{ $.Params.KUBECTL_VERSION }}
          command:
            - bash
            - -c
          args:
            - kubectl -n {{ $root.Namespace }} exec {{ $root.Name }}-node-{{ $v }} --container medusa-backup -- python3 /usr/local/bin/medusa backup --backup-name {{ $root.Params.BACKUP_NAME }}
      restartPolicy: Never
  backoffLimit: 0
{{ end }}