apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-enable-tls
  namespace: {{ .Namespace }}
data:
  enable-tls.sh: |
    #!/usr/bin/env bash
    set -e
    mkdir -p /etc/cassandra/tls
    pushd /etc/cassandra/tls
    # COPY CA AUTHORITY CERTIFICATE AND KEY OBTAINED FROM SECRETS
    cp /etc/tls/certs/tls.crt /etc/cassandra/tls/tls.crt
    cp /etc/tls/certs/tls.key /etc/cassandra/tls/tls.key
    # GENERATE KEYSTORE AND TRUSTSTORE
    keytool -keystore cassandra.server.keystore.jks \
            -alias localhost \
            -validity 900 \
            -genkey \
            -keyalg RSA \
            -dname "CN=$(hostname -f)" \
            -storepass changeit \
            -keypass changeit \
            -noprompt
    # Add the CACert to the client and server truststores so that clients and server can trust this CA
    keytool -keystore cassandra.client.truststore.jks \
            -alias CARoot \
            -import \
            -file /etc/cassandra/tls/tls.crt \
            -storepass changeit \
            -noprompt
    keytool -keystore cassandra.server.truststore.jks \
            -alias CARoot \
            -importcert \
            -file /etc/cassandra/tls/tls.crt \
            -storepass changeit \
            -noprompt
    # Create a certificate signing request
    keytool -keystore cassandra.server.keystore.jks \
            -alias localhost \
            -certreq \
            -file cert-req \
            -storepass changeit
    # Add openssl certificate signing extension config file
    cat > csr.conf <<EOF
    [ req_ext ]
    subjectAltName = @alt_names
    extendedKeyUsage = serverAuth, clientAuth
    
    [ alt_names ]
    DNS.1 = localhost
    DNS.2 = 127.0.0.1
    DNS.3 = $(hostname -f)
    DNS.4 = $(hostname -i)
    DNS.5 = $(hostname)
    IP.1 = 0.0.0.0
    IP.2 = 127.0.0.1
    IP.3 = $(hostname -i)
    EOF
    # Sign the certificate with the CA & CAKey
    openssl x509 -req \
        -CA /etc/cassandra/tls/tls.crt \
        -CAkey /etc/cassandra/tls/tls.key \
        -in cert-req \
        -out cert-signed \
        -days 900 \
        -CAcreateserial \
        -passin pass:changeit \
        -extfile csr.conf \
        -extensions req_ext
    # Import the CA cert into server keystore
    keytool -keystore cassandra.server.keystore.jks \
            -alias CARoot \
            -import \
            -file /etc/cassandra/tls/tls.crt \
            -storepass changeit -noprompt
    # Import the signed certificate into server keystore
    keytool -keystore cassandra.server.keystore.jks \
            -alias localhost \
            -import \
            -file cert-signed \
            -storepass changeit -noprompt
    popd
