apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-node-scripts
  namespace: {{ .Namespace }}
data:
  node-readiness-probe.sh: |
    {{ if ne $.Params.JMX_LOCAL_ONLY "true" }}
    nodetool --ssl status -p {{ .Params.JMX_PORT }} | grep -q "UN  ${POD_IP}"
    {{ else }}
    nodetool status -p {{ .Params.JMX_PORT }} | grep -q "UN  ${POD_IP}"
    {{ end }}
  node-liveness-probe.sh: |
    {{ if ne $.Params.JMX_LOCAL_ONLY "true" }}
    nodetool --ssl info
    {{ else }}
    nodetool info
    {{ end }}
  generate-rackdc-properties.sh: |
    # Generate the rackdc-properties
    RACK=`kubectl get node -L$RACKLABEL | grep ${NODE_NAME} | awk '{print $6}'`
    cat <<EOF > /etc/cassandra/cassandra-rackdc.properties
    dc=$CASSANDRA_DATACENTER
    rack=$RACK
    EOF
