{{ $auth_params := "" }}
{{ if .Params.AUTHENTICATION_SECRET_NAME }}
{{ $auth_params = "-u $(cat /etc/cassandra/authentication/username) -pw $(cat /etc/cassandra/authentication/password)" }}
{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-node-scripts
  namespace: {{ .Namespace }}
data:
  node-drain.sh: |
    {{ if ne $.Params.JMX_LOCAL_ONLY "true" }}
    nodetool {{ $auth_params }} --ssl drain
    {{ else }}
    nodetool {{ $auth_params }} drain
    {{ end }}
  node-readiness-probe.sh: |
    {{ if ne $.Params.JMX_LOCAL_ONLY "true" }}
    nodetool {{ $auth_params }} --ssl status -p {{ .Params.JMX_PORT }} | grep -q "UN  ${POD_IP}"
    {{ else }}
    nodetool {{ $auth_params }} status -p {{ .Params.JMX_PORT }} | grep -q "UN  ${POD_IP}"
    {{ end }}
  node-liveness-probe.sh: |
    {{ if ne $.Params.JMX_LOCAL_ONLY "true" }}
    nodetool {{ $auth_params }} --ssl info
    {{ else }}
    nodetool {{ $auth_params }} info
    {{ end }}
  generate-rackdc-properties.sh: |
    # Generate the rackdc-properties
    RACK=`kubectl get node -L$RACKLABEL | grep ${NODE_NAME} | awk '{print $6}'`
    cat <<EOF > /etc/cassandra/cassandra-rackdc.properties
    dc=$CASSANDRA_DATACENTER
    rack=$RACK
    EOF
