{{ $topology := list 1 }}
{{ if $.Params.NODE_TOPOLOGY }}
{{ $topology = $.Params.NODE_TOPOLOGY }}
{{ end }}
{{ range $datacenter := $topology }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  {{ if $.Params.NODE_TOPOLOGY }}
  name: {{ $.Name }}-{{ $datacenter.datacenter }}-pdb
  {{ else }}
  name: {{ $.Name }}-pdb
  {{ end }}
  namespace: {{ $.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $.Name }}
      cassandra: {{ $.OperatorName }}
      cassandra-dc: {{ $.OperatorName }}-{{ $datacenter.datacenter }}
      kudo.dev/instance: {{ $.Name }}
  minAvailable:
{{ end }}