apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Name }}-pdb
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Name }}
      cassandra: {{ .OperatorName }}
      kudo.dev/instance: {{ .Name }}
  maxUnavailable: {{ .Params.MAX_UNAVAILABLE_NODES }}