---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Name }}-node-repair-job
  namespace: {{ $.Namespace }}
  labels:
    cassandra: {{ $.OperatorName }}
    app: {{ $.Name }}
spec:
  template:
    spec:
      containers:
        - name: repair-job
          image: bitnami/kubectl:latest
          command: ["/bin/bash"]
          args: [ "-c", "kubectl exec {{ $.Params.REPAIR_POD }} -- nodetool {{ if $.Params.AUTHENTICATION_CREDENTIALS_SECRET }}-u $SECRET_USERNAME -pw $SECRET_PASSWORD{{ end }} repair"]
          {{ if $.Params.AUTHENTICATION_CREDENTIALS_SECRET }}
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Params.AUTHENTICATION_CREDENTIALS_SECRET }}
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Params.AUTHENTICATION_CREDENTIALS_SECRET }}
                  key: password
          {{ end }}
      restartPolicy: Never
      serviceAccountName: {{ .Name }}-node-repairer
