apiVersion: v1
kind: Service
metadata:
  name: svc
  {{ if eq .Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
  labels:
    "kudo.dev/servicemonitor": "true"
  {{ end }}
spec:
  ports:
    - port: {{ .Params.STORAGE_PORT }}
      name: storage
    - port: {{ .Params.SSL_STORAGE_PORT }}
      name: ssl-storage
    - port: {{ .Params.NATIVE_TRANSPORT_PORT }}
      name: native-transport
    {{ if .Params.START_RPC }}
    - port: {{ .Params.RPC_PORT }}
      name: rpc
    {{ end }}
    - port: {{ .Params.JMX_PORT }}
      name: jmx
    {{ if eq .Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
    - port: {{ .Params.PROMETHEUS_EXPORTER_PORT }}
      name: prometheus-exporter-port
    {{ end }}
  clusterIP: None
  selector:
    app: cassandra
    kudo.dev/instance: {{ .Name }}
