NODE_COUNT:
  description: "Number of Cassandra nodes"
  displayName: "Node Count"
  default: 3

NODE_CPUS:
  description: "CPUs (request) for the Cassandra node pods. spec.containers[].resources.requests.cpu"
  default: "2000m"

NODE_CPUS_LIMIT:
  description: "CPUs (limit) for the Cassandra node pods. spec.containers[].resources.limits.cpu"
  default: "2000m"

NODE_MEM:
  description: "Memory (request) for the Cassandra node pods. spec.containers[].resources.requests.memory"
  default: 4096

NODE_MEM_LIMIT:
  description: "Memory (limit) for the Cassandra node pods. spec.containers[].resources.limits.memory"
  default: 4096

STORAGE_PORT:
  description: "The port for inter-node communication."
  default: "7000"

SSL_STORAGE_PORT:
  description: "The port for inter-node communication over SSL."
  default: "7001"

NATIVE_TRANSPORT_PORT:
  description: "The port for CQL communication."
  default: "9042"

RPC_PORT:
  description: "The port for Thrift RPC communication."
  default: "9160"

JMX_PORT:
  description: "The JMX port that will be used to interface with the Cassandra application."
  default: "7199"

DISK_SIZE:
  description: "Disk size for the nodes"
  default: "20Gi"

STORAGE_CLASS:
  description: "The storage class to be used in volumeClaimTemplates. By default its not required and the default storage class is used."
  required: false

PERSISTENT_STORAGE:
  description: "If false, ephemeral storage is used. Not recommended for production use."
  default: "true"

CLUSTER_NAME:
  description: "The name of the cluster managed by the Service"
  default: "cassandra"

SEED_PROVIDER_CLASS:
  description: "The class within Cassandra that handles the seed logic."
  default: "org.apache.cassandra.locator.SimpleSeedProvider"

NUM_TOKENS:
  description: "The number of tokens assigned to each node."
  default: 256

HINTED_HANDOFF_ENABLED:
  description: "If true, hinted handoff is enabled for the cluster."
  default: true

MAX_HINT_WINDOW_IN_MS:
  description: "The maximum amount of time, in ms, that hints are generates hints for an unresponsive node."
  default: 10800000

HINTED_HANDOFF_THROTTLE_IN_KB:
  description: "The maximum throttle per delivery thread in kilobytes per second."
  default: 1024

MAX_HINTS_DELIVERY_THREADS:
  description: "The maximum number of delivery threads for hinted handoff."
  default: 2

BATCHLOG_REPLAY_THROTTLE_IN_KB:
  description: "The total throttle for log replay in Kpbs."
  default: 1024

PARTITIONER:
  description: "The partitioner used to distribute rows across the cluster. Murmur3Partitioner is the recommended setting. RandomPartitioner and ByteOrderedPartitioner are supported for legacy applications."
  default: "org.apache.cassandra.dht.Murmur3Partitioner"

KEY_CACHE_SAVE_PERIOD:
  description: "The duration in seconds that keys are saved in cache. Saved caches greatly improve cold-start speeds and has relatively little effect on I/O."
  default: 14400

ROW_CACHE_SIZE_IN_MB:
  description: "Maximum size of the row cache in memory. Row cache can save more time than key_cache_size_in_mb, but is space-intensive because it contains the entire row. Use the row cache only for hot rows or static rows. 0 disables the row cache."
  default: 0

ROW_CACHE_SAVE_PERIOD:
  description: "Duration in seconds that rows are saved in cache. 0 disables caching."
  default: 0

COMMITLOG_SYNC_PERIOD_IN_MS:
  description: "The number of milliseconds between disk fsync calls."
  default: 10000

COMMITLOG_SYNC_BATCH_WINDOW_IN_MS:
  description: "Time to wait between batch fsyncs, if commitlog_sync is in batch mode then default value should be: 2"
  default: ""

COMMITLOG_SEGMENT_SIZE_IN_MB:
  description: "The size of each commit log segment in Mb."
  default: 32

CONCURRENT_READS:
  description: "For workloads with more data than can fit in memory, the bottleneck is reads fetching data from disk. Setting to (16 times the number of drives) allows operations to queue low enough in the stack so that the OS and drives can reorder them."
  default: 16

CONCURRENT_WRITES:
  description: "Writes in Cassandra are rarely I/O bound, so the ideal number of concurrent writes depends on the number of CPU cores in your system. The recommended value is 8 times the number of cpu cores."
  default: 32

CONCURRENT_COUNTER_WRITES:
  description: "Counter writes read the current values before incrementing and writing them back. The recommended value is (16 times the number of drives) ."
  default: 16

MEMTABLE_ALLOCATION_TYPE:
  description: "The type of allocations for the Cassandra memtable. heap_buffers keep all data on the JVM heap. offheap_buffers may reduce heap utilization for large string or binary values. offheap_objects may improve heap size for small integers or UUIDs as well. Both off heap options will increase read latency."
  default: "heap_buffers"

INDEX_SUMMARY_RESIZE_INTERVAL_IN_MINUTES:
  description: "How frequently index summaries should be re-sampled in minutes. This is done periodically to redistribute memory from the fixed-size pool to SSTables proportional their recent read rates."
  default: 60

START_NATIVE_TRANSPORT:
  description: "If true CQL is enabled."
  default: true

START_RPC:
  description: "If true Thrift RPC is enabled. This is deprecated but may be necessary for legacy applications."
  default: false

RPC_KEEPALIVE:
  description: "Enables or TCP keepalive for RPC connections."
  default: true

THRIFT_FRAMED_TRANSPORT_SIZE_IN_MB:
  description: "Frame size (maximum field length) for Thrift."
  default: 15

TOMBSTONE_WARN_THRESHOLD:
  description: "The maximum number of tombstones a query can scan before warning."
  default: 1000

TOMBSTONE_FAILURE_THRESHOLD:
  description: "The maximum number of tombstones a query can scan before aborting."
  default: 100000

COLUMN_INDEX_SIZE_IN_KB:
  description: "The granularity of the index of rows within a partition. For huge rows, decrease this setting to improve seek time. If you use key cache, be careful not to make this setting too large because key cache will be overwhelmed."
  default: 64

BATCH_SIZE_WARN_THRESHOLD_IN_KB:
  description: "Warn the operator on a batch size exceeding this value in kilobytes. Caution should be taken on increasing the size of this threshold as it can lead to node instability."
  default: 5

BATCH_SIZE_FAIL_THRESHOLD_IN_KB:
  description: "Fail batch sizes exceeding this value in kilobytes. Caution should be taken on increasing the size of this threshold as it can lead to node instability."
  default: 50

COMPACTION_THROUGHPUT_MB_PER_SEC:
  description: "Throttles compaction to the specified total throughput across the node. Compaction frequency varies with direct proportion to write throughput and is necessary to limit the SSTable size. The recommended value is 16 to 32 times the rate of write throughput (in MB/second)."
  default: 16

SSTABLE_PREEMPTIVE_OPEN_INTERVAL_IN_MB:
  description: "When compacting, the replacement opens SSTables before they are completely written and uses in place of the prior SSTables for any range previously written. This setting helps to smoothly transfer reads between the SSTables by reducing page cache churn and keeps hot rows hot."
  default: 50

READ_REQUEST_TIMEOUT_IN_MS:
  description: "The time that the coordinator waits for read operations to complete in ms."
  default: 5000

RANGE_REQUEST_TIMEOUT_IN_MS:
  description: "The time that the coordinator waits for range scans complete in ms."
  default: 10000

WRITE_REQUEST_TIMEOUT_IN_MS:
  description: "The time that the coordinator waits for write operations to complete in ms."
  default: 2000

COUNTER_WRITE_REQUEST_TIMEOUT_IN_MS:
  description: "The time that the coordinator waits for counter write operations to complete in ms."
  default: 5000

CAS_CONTENTION_TIMEOUT_IN_MS:
  description: "The time for which the coordinator will retry CAS operations on the same row in ms."
  default: 1000

TRUNCATE_REQUEST_TIMEOUT_IN_MS:
  description: "The time that the coordinator waits for truncate operations to complete in ms."
  default: 60000

REQUEST_TIMEOUT_IN_MS:
  description: "The default timeout for all other requests in ms."
  default: 10000

DYNAMIC_SNITCH_UPDATE_INTERVAL_IN_MS:
  description: "The time, in ms, the snitch will wait before updating node scores."
  default: 100

DYNAMIC_SNITCH_RESET_INTERVAL_IN_MS:
  description: "The time, in ms, the snitch will wait before resetting node scores allowing bad nodes to recover."
  default: 600000

DYNAMIC_SNITCH_BADNESS_THRESHOLD:
  description: "Sets the performance threshold for dynamically routing client requests away from a poorly performing node."
  default: 0.1

INTERNODE_COMPRESSION:
  description: "Controls whether traffic between nodes is compressed. all compresses all traffic. none compresses no traffic. dc compresses between datacenters."
  default: "all"

MAX_HINTS_FILE_SIZE_IN_MB:
  description: "The maximum size of the hints file in Mb."
  default: 128

HINTS_FLUSH_PERIOD_IN_MS:
  description: "The time, in ms, for the period in which hints are flushed to disk."
  default: 10000

CONCURRENT_MATERIALIZED_VIEW_WRITES:
  description: "The maximum number of concurrent writes to materialized views."
  default: 32

COMMITLOG_TOTAL_SPACE_IN_MB:
  description: "The total size of the commit log in Mb."
  default: 8192

AUTO_SNAPSHOT:
  description: "Take a snapshot of the data before truncating a keyspace or dropping a table"
  default: true

KEY_CACHE_KEYS_TO_SAVE:
  description: "The number of keys from the key cache to save"
  default: 100

ROW_CACHE_KEYS_TO_SAVE:
  description: "The number of keys from the row cache to save"
  default: 100

COUNTER_CACHE_KEYS_TO_SAVE:
  description: "The number of keys from the counter cache to save"
  default: 100

FILE_CACHE_SIZE_IN_MB:
  description: "The total memory to use for SSTable-reading buffers"
  default: 512

MEMTABLE_HEAP_SPACE_IN_MB:
  description: "The amount of on-heap memory allocated for memtables"
  default: 2048

MEMTABLE_OFFHEAP_SPACE_IN_MB:
  description: "The total amount of off-heap memory allocated for memtables"
  default: 2048

MEMTABLE_CLEANUP_THRESHOLD:
  description: "The ratio used for automatic memtable flush"
  default: 0.11

MEMTABLE_FLUSH_WRITERS:
  description: "The number of memtable flush writer threads"
  default: 2

LISTEN_ON_BROADCAST_ADDRESS:
  description: "Listen on the address set in broadcast_address property"
  default: false

INTERNODE_AUTHENTICATOR:
  description: "The internode authentication backend"
  default: "org.apache.cassandra.auth.AllowAllInternodeAuthenticator"

NATIVE_TRANSPORT_MAX_THREADS:
  description: "The maximum number of thread handling requests"
  default: 128

NATIVE_TRANSPORT_MAX_FRAME_SIZE_IN_MB:
  description: "The maximum allowed size of a frame"
  default: 256

NATIVE_TRANSPORT_MAX_CONCURRENT_CONNECTIONS:
  description: "The maximum number of concurrent client connections"
  default: -1

NATIVE_TRANSPORT_MAX_CONCURRENT_CONNECTIONS_PER_IP:
  description: "The maximum number of concurrent client connections per source IP address"
  default: -1

RPC_MIN_THREADS:
  description: "The minimum thread pool size for remote procedure calls"
  default: 16

RPC_MAX_THREADS:
  description: "The maximum thread pool size for remote procedure calls"
  default: 2048

RPC_SEND_BUFF_SIZE_IN_BYTES:
  description: "The sending socket buffer size in bytes for remote procedure calls"
  default: 16384

RPC_RECV_BUFF_SIZE_IN_BYTES:
  description: "The receiving socket buffer size for remote procedure calls"
  default: 16384

CONCURRENT_COMPACTORS:
  description: "The number of concurrent compaction processes allowed to run simultaneously on a node"
  default: 1

STREAM_THROUGHPUT_OUTBOUND_MEGABITS_PER_SEC:
  description: "The maximum throughput of all outbound streaming file transfers on a node"
  default: 200

INTER_DC_STREAM_THROUGHPUT_OUTBOUND_MEGABITS_PER_SEC:
  description: "The maximum throughput of all streaming file transfers between datacenters"
  default: 200

STREAMING_KEEP_ALIVE_PERIOD_IN_SECS:
  description: "Interval to send keep-alive messages. The stream session fails when a keep-alive message is not received for 2 keep-alive cycles."
  default: 300

PHI_CONVICT_THRESHOLD:
  description: "The sensitivity of the failure detector on an exponential scale"
  default: 8

BUFFER_POOL_USE_HEAP_IF_EXHAUSTED:
  description: "Allocate on-heap memory when the SSTable buffer pool is exhausted"
  default: true

DISK_OPTIMIZATION_STRATEGY:
  description: "The strategy for optimizing disk reads"
  default: "ssd"

MAX_VALUE_SIZE_IN_MB:
  description: "The maximum size of any value in SSTables"
  default: 256

OTC_COALESCING_STRATEGY:
  description: "The strategy to use for coalescing network messages"
  default: "DISABLED"

UNLOGGED_BATCH_ACROSS_PARTITIONS_WARN_THRESHOLD:
  description: "Causes Cassandra to log a WARN message on any batches not of type LOGGED that span across more partitions than this limit."
  default: 10

COMPACTION_LARGE_PARTITION_WARNING_THRESHOLD_MB:
  description: "Cassandra logs a warning when compacting partitions larger than the set value."
  default: 100

REQUEST_SCHEDULER:
  description: "The scheduler to handle incoming client requests according to a defined policy. This scheduler is useful for throttling client requests in single clusters containing multiple keyspaces."
  default: "org.apache.cassandra.scheduler.NoScheduler"

INTER_DC_TCP_NODELAY:
  description: "Enable this property for inter-datacenter communication."
  default: false

TRACETYPE_QUERY_TTL:
  description: "TTL for different trace types used during logging of the query process."
  default: 86400

TRACETYPE_REPAIR_TTL:
  description: "TTL for different trace types used during logging of the repair process."
  default: 604800

GC_WARN_THRESHOLD_IN_MS:
  description: "Any GC pause longer than this interval is logged at the WARN level."
  default: 1000

WINDOWS_TIMER_INTERVAL:
  description: "The default Windows kernel timer and scheduling resolution is 15.6ms for power conservation. Lowering this value on Windows can provide much tighter latency and better throughput, however some virtualized environments may see a negative performance impact from changing this setting below their system default."
  default: 1

COUNTER_CACHE_SAVE_PERIOD:
  description: "the amount of time after which Cassandra saves the counter cache (keys only)."
  default: 7200

TRICKLE_FSYNC_INTERVAL_IN_KB:
  description: "The size of the fsync in kilobytes."
  default: 10240

TRICKLE_FSYNC:
  description: "When set to true, causes fsync to force the operating system to flush the dirty buffers at the set interval "
  default: false

INCREMENTAL_BACKUPS:
  description: "Backs up data updated since the last snapshot was taken. When enabled, Cassandra creates a hard link to each SSTable flushed or streamed locally in a backups subdirectory of the keyspace data."
  default: false

SNAPSHOT_BEFORE_COMPACTION:
  description: "Enables or disables taking a snapshot before each compaction. A snapshot is useful to back up data when there is a data format change."
  default: false

CROSS_NODE_TIMEOUT:
  description: "operation timeout information exchange between nodes (to accurately measure request timeouts)."
  default: false

COMMIT_FAILURE_POLICY:
  description: "Policy for commit disk failures."
  default: "stop"

KEY_CACHE_SIZE_IN_MB:
  description: "A global cache setting for the maximum size of the key cache in memory (for all tables). "
  default: ""

COUNTER_CACHE_SIZE_IN_MB:
  description: "When no value is set, Cassandra uses the smaller of minimum of 2.5% of Heap or 50MB."
  default: ""

COMMITLOG_SYNC:
  description: "The method that Cassandra uses to acknowledge writes in milliseconds"
  default: "periodic"

INDEX_SUMMARY_CAPACITY_IN_MB:
  description: "Fixed memory pool size in MB for SSTable index summaries."
  default: ""

RPC_SERVER_TYPE:
  description: "Cassandra provides three options for the RPC server. sync and hsha performance is about the same, but hsha uses less memory."
  default: "sync"

ENDPOINT_SNITCH:
  description: "Set to a class that implements the IEndpointSnitch interface. Cassandra uses the snitch to locate nodes and route requests."
  default: "SimpleSnitch"

DISK_FAILURE_POLICY:
  description: "The policy for how Cassandra responds to disk failure"
  default: "stop"

ENABLE_USER_DEFINED_FUNCTIONS:
  description: " User defined functions (UDFs) present a security risk, since they are executed on the server side. UDFs are executed in a sandbox to contain the execution of malicious code."
  default: false

ENABLE_SCRIPTED_USER_DEFINED_FUNCTIONS:
  description: "Java UDFs are always enabled, if enable_user_defined_functions is true. Enable this option to use UDFs with language javascript or any custom JSR-223 provider. This option has no effect if enable_user_defined_functions is false"
  default: false

CDC_ENABLED:
  description: "Enable / disable CDC functionality on a per-node basis. This modifies the logic used for write path allocation rejection"
  default: false

CDC_TOTAL_SPACE_IN_MB:
  description: "Total space to use for change-data-capture (CDC) logs on disk. "
  default: 4096

CDC_FREE_SPACE_CHECK_INTERVAL_MS:
  description: "Interval between checks for new available space for CDC-tracked tables when the cdc_total_space_in_mb threshold is reached and the CDCCompactor is running behind or experiencing back pressure."
  default: 250

PREPARED_STATEMENTS_CACHE_SIZE_MB:
  description: "Maximum size of the native protocol prepared statement cache"
  default: ""

THRIFT_PREPARED_STATEMENTS_CACHE_SIZE_MB:
  description: "Maximum size of the Thrift prepared statement cache. Leave empty if you do not use Thrift."
  default: ""

COLUMN_INDEX_CACHE_SIZE_IN_KB:
  description: "A threshold for the total size of all index entries for a partition that the database stores in the partition key cache."
  default: 2

SLOW_QUERY_LOG_TIMEOUT_IN_MS:
  description: "How long before a node logs slow queries. Select queries that exceed this value generate an aggregated log message to identify slow queries. To disable, set to 0."
  default: 500

BACK_PRESSURE_ENABLED:
  description: "Enable for the coordinator to apply the specified back pressure strategy to each mutation that is sent to replicas."
  default: false

BACK_PRESSURE_STRATEGY_CLASS:
  description: "The back-pressure strategy applied. The default implementation, RateBasedBackPressure, takes three arguments: high ratio, factor, and flow type, and uses the ratio between incoming mutation responses and outgoing mutation requests."
  default: "org.apache.cassandra.net.RateBasedBackPressure"

BACK_PRESSURE_HIGH_RATIO:
  description: "When outgoing mutations are below this value, they are rate limited according to the incoming rate decreased by the factor. When above this value, the rate limiting is increased by the factor."
  default: 0.9

BACK_PRESSURE_FACTOR:
  description: "A number between 1 and 10. Increases or decreases rate limiting."
  default: 5

BACK_PRESSURE_FLOW:
  description: "The flow speed to apply rate limiting: FAST - rate limited to the speed of the fastest replica. SLOW - rate limit to the speed of the slowest replica."
  default: "FAST"