FROM ${MEDUSA_BACKUP_DOCKER_IMAGE_FROM}

COPY medusa/medusa-frontend.py /

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends sudo libc6-dev gcc python3-dev python3-pip python3-setuptools groff vim; \
    sudo pip3 install awscli cassandra-medusa[S3]==${MEDUSA_BACKUP_VERSION}

CMD [ "python3", "/medusa-frontend.py" ]

USER root
