FROM ${MEDUSA_BACKUP_DOCKER_IMAGE_FROM}

COPY medusa/medusa-frontend.py /
COPY medusa/cassandra-sudoer /etc/sudoers.d/

COPY medusa/medusa-src /medusa-src
COPY medusa/requirements.txt /

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends sudo libc6-dev libev-dev libssl-dev zlib1g-dev libffi-dev gcc make cmake awscli python3-dev python3-pip python3-setuptools groff vim; \
    cd medusa-src; \
    python3 setup.py  install

USER root
