FROM ${MEDUSA_BACKUP_DOCKER_IMAGE_FROM}

COPY medusa/cassandra-sudoer /etc/sudoers.d/

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update; \
    apt-get install -y --no-install-recommends sudo libc6-dev libev-dev gcc make cmake python3-dev python3-pip openssl libssl-dev zlib1g-dev groff vim; \
    sudo pip3 install setuptools wheel fasteners; \
    sudo pip3 install awscli cassandra-medusa[S3]==${MEDUSA_BACKUP_VERSION}

CMD [ "sleep", "infinity" ]

USER root
